// ─────────────────────────────────────────────────────────────────────────────
// app/page.tsx — Atlanta Gleaner home page
//
// Shows the most recently decided opinion as the featured case.
// Layout: Banner → ResizablePanels (NewsBox | CaseLawBox | AstrologyBox)
// Data source: src/data/cases.json (auto-generated by scripts/process-cases.js)
// ─────────────────────────────────────────────────────────────────────────────

import React from 'react'
import { PALETTE }         from '@/src/styles/tokens'
import { Banner }          from '@/src/components/Banner'
import { NewsBox }         from '@/src/components/NewsBox'
import CaseLawBox          from '@/src/components/CaseLawBox'
import { AstrologyBox }    from '@/src/components/AstrologyBox'
import { ResizablePanels } from '@/src/components/ResizablePanels'
import casesRaw            from '@/src/data/cases.json'
import type { CaseLaw }    from '@/src/data/types'

const cases = casesRaw as CaseLaw[]

export default function HomePage() {
  // Feature the Girls Galore case; fall back to newest if not found
  const featured = cases.find((c) => c.title === 'Girls Galore, Inc. v. City of Atlanta') || (() => {
    const sorted = [...cases].sort((a, b) => {
      const da = new Date(a.dateDecided).getTime() || 0
      const db = new Date(b.dateDecided).getTime() || 0
      return db - da
    })
    return sorted[0]
  })()

  return (
    <main style={{ minHeight: '100vh', background: PALETTE.warm }}>
      <Banner />
      <ResizablePanels
        left={{
          label: 'Latest News',
          node:  <NewsBox />,
        }}
        center={{
          label: 'Case Law Updates',
          node:  <CaseLawBox caseData={featured} label="Case Law Updates" />,
        }}
        right={{
          label: 'Astrology',
          node:  <AstrologyBox />,
        }}
      />
    </main>
  )
}
