// ─────────────────────────────────────────────────────────────────────────────
// app/page.tsx — Atlanta Gleaner home page
//
// Shows the most recently decided opinion as the featured case.
// Layout: Banner → ResizablePanels (NewsBox | CaseLawBox | FarSideBox)
// Data source: src/data/cases.json (auto-generated by scripts/process-cases.js)
// ─────────────────────────────────────────────────────────────────────────────

import React from 'react'
import { Banner }          from '@/src/components/Banner'
import { NewsBox }         from '@/src/components/NewsBox'
import CaseLawBox          from '@/src/components/CaseLawBox'
import { FarSideBox }      from '@/src/components/FarSideBox'
import { ResizablePanels } from '@/src/components/ResizablePanels'
import casesRaw            from '@/src/data/cases.json'
import type { CaseLaw }    from '@/src/data/types'

const cases = casesRaw as CaseLaw[]

export default function HomePage() {
  // Sort by dateDecided, newest first
  const sorted = [...cases].sort((a, b) => {
    const da = new Date(a.dateDecided).getTime() || 0
    const db = new Date(b.dateDecided).getTime() || 0
    return db - da
  })

  const featured = sorted[0]

  return (
    <main className="min-h-screen bg-[#EEEDEB]">
      <Banner />
      <ResizablePanels
        left={{
          label: 'Latest News',
          node:  <NewsBox />,
        }}
        center={{
          label: 'Notable Decisions',
          node:  <CaseLawBox caseData={featured} label="Notable Decisions" />,
        }}
        right={{
          label: 'The Far Side',
          node:  <FarSideBox />,
        }}
      />
    </main>
  )
}
